### PR TITLE
Add config schema.

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Comment by dhylands** [comment]
I git cloned the serial-adapter into my .mozilla-iot/addons directory and checked out this PR. If I click Configure on the serial-adapter I get a blank screen.

**Comment by mrstegeman** [comment]
@dhylands Can you pull latest master on the gateway, run `yarn`, and try this updated PR? Seems to work better for me.

**Comment by dhylands** [comment]
So what I did was this
* checked out master version of the gateway
* ran yarn
* checked out master version of serial-adapter into .mozilla-iot/addons/serial-adapter
* removed .mozilla-iot/config/*
* ran npm start
* ran `config-editor.py serial-adapter` and confirmed that it showed:
```
{
  "ports": {
    "arduino-usb": {
      "manufacturer": "Arduino"
    }
  }
}
```
* killed the gateway
* checkout PR #3 of the serial-adapter
* npm start the gateway
* created my first user in the UI and enabled the serial adapter
As soon as I enabled the serial-adapter it spewed the following continuously:
```
2018-04-04 14:57:42.561 serial: Opening database: /home/dhylands/Dropbox/moziot/.mozilla-iot/config/db.sqlite3
2018-04-04 14:57:42.573 serial: Loading add-on for serial-adapter from /home/dhylands/Dropbox/moziot/.mozilla-iot/addons/serial-adapter
2018-04-04 14:57:42.672 serial: /home/dhylands/Dropbox/moziot/gateway/node_modules/gateway-addon/node_modules/sqlite3/lib/trace.js:27
2018-04-04 14:57:42.672 serial:                     throw err;
2018-04-04 14:57:42.672 serial:                     ^
2018-04-04 14:57:42.672 serial: 
2018-04-04 14:57:42.672 serial: TypeError: Cannot read property 'value' of undefined
2018-04-04 14:57:42.672 serial:     at Statement.conn.get (/home/dhylands/Dropbox/moziot/gateway/node_modules/gateway-addon/lib/database.js:98:41)
2018-04-04 14:57:42.672 serial: --> in Database#get('SELECT value FROM settings WHERE key = ?', [ 'addons.serial-adapter' ], [Function])
2018-04-04 14:57:42.673 serial:     at Promise (/home/dhylands/Dropbox/moziot/gateway/node_modules/gateway-addon/lib/database.js:91:17)
2018-04-04 14:57:42.673 serial:     at new Promise (<anonymous>)
2018-04-04 14:57:42.673 serial:     at Database.loadConfig (/home/dhylands/Dropbox/moziot/gateway/node_modules/gateway-addon/lib/database.js:90:12)
2018-04-04 14:57:42.673 serial:     at loadSerial (/home/dhylands/Dropbox/moziot/.mozilla-iot/addons/serial-adapter/serial-adapter.js:350:18)
2018-04-04 14:57:42.673 serial:     at pluginClient.register.then (/home/dhylands/Dropbox/moziot/gateway/src/addon-loader.js:81:7)
2018-04-04 14:57:42.673 serial:     at <anonymous>
2018-04-04 14:57:42.673 serial:     at process._tickCallback (internal/process/next_tick.js:188:7)
2018-04-04 14:57:42.675 Plugin: serial-adapter died, code = 1 restarting...

```

**Comment by dhylands** [comment]
This problem seems to be cause by the plugin trying to use a database from `~/.mozilla-iot` when my profileDir is set like:
```
profileDir: `${home}/Dropbox/moziot/.mozilla-iot`,
```
If make ~/.mozilla-iot be a symlink to the real location then this problem goes away

**Review by dhylands — APPROVED** [review]

**Pull request merged**
